services:

  api:
    build:
      context: .
    volumes:
        - ./:/app
        - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env 
    command: npm run dev
    restart: always
